# Introducing Julia

Julia is a fast, dynamic language designed for numerical and scientific computing. Julia's syntax is superficially similar to Python, MATLAB, and other familiar languages, but its sophisticated compiler is able to produce native code with similar performance to C and FORTRAN.

### Julia is...

* Fast. Check out the next notebook for some evidence. 
* Free. That means you are free to do whatever you want with Julia (including developing proprietary tools) forever. 
* Open-Source: The source code for Julia itself is available at https://github.com/julialang/julia and the source code for all of the packages used in this demo can be found on Github as well. 


### Julia is *not*...

* ROS. Nor is Julia a complete solution for robotics development. It's a programming language that makes it easier to create the tools you need, but it doesn't have all those tools yet. We're working on it! 
* Object-Oriented. Julia uses *multiple dispatch* to organize functions and behaviors. 
* Finished. Julia v1.0 is coming summer 2018, but it's not available as of this talk (May 2018). There will be changes between the code you see here and what will be recommended in 1.0. 


## Getting Julia

You can install Julia from <https://julialang.org/downloads/>. This document was designed with Julia v0.6.2 in mind, but should work correctly with any 0.6.x version. 

## Getting Help

For help with this tutorial, you can open a new issue here: <https://github.com/rdeits/DynamicWalking2018.jl/issues>. For general help with Julia usage, try the [Julia forum](https://discourse.julialang.org/) or the [Julia Slack chat group](https://slackinvite.julialang.org/)

## Starting Julia

On Mac or Windows, just run the "Julia" executable. On Linux, you can run the `julia` binary or [add it to your path](https://julialang.org/downloads/platform.html#generic-linux-binaries). At startup, you will see the Julia REPL, where you can run Julia commands: 

![Julia REPL in terminal](img/julia-repl.png)

## Other Julia Environments

For a more full-featured Julia environment, check out: 

### Julia IDEs

* Juno: A Julia IDE built on top of Atom: http://junolab.org/
* Julia-VSCode: A Julia IDE plugin for the VSCode editor: https://github.com/JuliaEditorSupport/julia-vscode

### JuliaPro

[JuliaPro](https://juliacomputing.com/products/juliapro.html) is a self-contained commercial Julia environment and IDE (based on Juno). This tutorial *will not* work properly in JuliaPro (as of May 2018) because we need a number of packages not included in that bundle. 

### Jupyter Support

Julia works very well in [Jupyter notebooks](http://jupyter.org/). In fact, this document was created using Julia in a Jupyter notebook. To use Julia with Jupyter, you will need the [IJulia](https://github.com/JuliaLang/IJulia.jl) package. 

# Using Julia

Basic Julia operations will look familiar to those with MATLAB or Python experience:

In [1]:
2 + 2

4

In [2]:
println("hello world")

hello world


# Arrays

Julia has built-in support for arrays with arbitrary element types and arbitrary numbers of dimensions:

In [3]:
# Vectors:

x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
# Matrices:

x = [1 2
     3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [5]:
# N-dimensional arrays:

x = ones(2, 2, 2)

2×2×2 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0
 1.0  1.0

[:, :, 2] =
 1.0  1.0
 1.0  1.0

Indexing and slicing arrays is also easy. Julia's Array type uses a 1-based index (like FORTRAN and MATLAB) and stores its entries in column-major order (like FORTRAN and MATLAB). 

In [6]:
x = [1 2
     3 4]

x[1, 1]

1

In [7]:
x[:, 1]

2-element Array{Int64,1}:
 1
 3

In [8]:
x[:, end]

2-element Array{Int64,1}:
 2
 4

Of course, we can do more than just create and index arrays. For example: 

In [9]:
# Seed the random number generator so that it will
# produce the same set of random numbers. 
#
# You don't generally need to do this, but it ensures
# that you'll see exactly the same results we do for
# this demo. 
srand(42);

In [10]:
x = rand(4, 4)

4×4 Array{Float64,2}:
 0.533183   0.958926  0.956916  0.422956
 0.454029   0.973566  0.584284  0.602298
 0.0176868  0.30387   0.937466  0.363458
 0.172933   0.176909  0.160006  0.383491

In [11]:
x .+ 1 # The `.` notation applies a function elementwise:

4×4 Array{Float64,2}:
 1.53318  1.95893  1.95692  1.42296
 1.45403  1.97357  1.58428  1.6023 
 1.01769  1.30387  1.93747  1.36346
 1.17293  1.17691  1.16001  1.38349

In [12]:
# Unlike in MATLAB, the `.` notation works for *any function*:
sin.(x)

4×4 Array{Float64,2}:
 0.508277   0.818575  0.817419  0.410458
 0.43859    0.826896  0.551602  0.566537
 0.0176859  0.299215  0.806061  0.355509
 0.172072   0.175987  0.159324  0.37416 

In [13]:
inv(x) * x

4×4 Array{Float64,2}:
  1.0          -1.11022e-15  -1.66533e-15  -8.88178e-16
  0.0           1.0           1.11022e-16   0.0        
 -1.38778e-17   1.73472e-17   1.0          -6.93889e-17
 -5.55112e-17  -5.55112e-17   0.0           1.0        

We might expect to see `inv(x) * x` yield exactly the identity, but this doesn't happen due to the rounding issues which are present in all floating-point math (in any language).

Fortunately, Julia has excellent support for arrays with arbitrary element types, so let's compute the inverse in exact, rational arithmetic instead: 

In [14]:
x_rational = Rational{BigInt}.(x)

4×4 Array{Rational{BigInt},2}:
 2401242832375411//4503599627370496  …   476206419934121//1125899906842624
 2044765445845603//4503599627370496     1356253579026917//2251799813685248
     311149946105//17592186044416        818435606833973//2251799813685248
  778821124680505//4503599627370496     1727090801564085//4503599627370496

In [15]:
inv(x_rational) * x_rational

4×4 Array{Rational{BigInt},2}:
 1//1  0//1  0//1  0//1
 0//1  1//1  0//1  0//1
 0//1  0//1  1//1  0//1
 0//1  0//1  0//1  1//1

# Functions

Defining and using a function in Julia is easy: 

In [16]:
function say_hello(name)
    println("hello ", name)
end

say_hello (generic function with 1 method)

In [17]:
say_hello("world")

hello world


By default, a function is generic, so you can pass in any type you want: 

In [18]:
say_hello([1, 2, 3])

hello [1, 2, 3]


But Julia also allows you express restrictions on a particular method's input types. We can define a function multiple times with different type signatures, and Julia will always pick the most specific signature that matches our inputs: 

In [19]:
# a special greeting for numbers
function say_hello(x::Number)
    println("hello number ", x)
end

# An even more special greeting for floating-point numbers
function say_hello(x::Float64)
    println("hello Float64 ", x)
end

say_hello(5)   # 5 is an Int, and Int is a kind of Number, so we get the say_hello(x::Number) method
say_hello(5.0) # 5.0 is a Float64, and Float64 is more specific than Number, so wet get say_hello(x::Float64)

hello number 5
hello Float64 5.0


Julia also has a short one-line syntax for defining simple functions: 

In [20]:
say_goodbye(name) = println("goodbye ", name)

say_goodbye (generic function with 1 method)

In [21]:
say_goodbye("world")

goodbye world


The last expression inside a function is automatically returned as its result (but you can also use the explicit `return` keyword if you prefer). 

In [22]:
function add(x, y)
    x + y
end

# Or, equivalently, we could write:
# add(x, y) = x + 1

add(1, 2)

3

# Types

Julia values have types, and you can create your own types to organize and control your code: 

In [23]:
typeof(1.0)

Float64

In [24]:
typeof(2)

Int64

In [25]:
typeof(0x03)

UInt8

In [26]:
typeof([1, 2, 3])

Array{Int64,1}

In [27]:
convert(Array{Float64, 1}, [1, 2, 3])

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [28]:
struct Person
  name::String
  age::Int
end

alice = Person("Alice", 42)

Person("Alice", 42)

Julia's types are extremely lightweight, and user-defined types are *exactly* as performant as anything built-in:

In [29]:
sizeof(Person) == sizeof(Ptr{String}) + sizeof(Int)

true

# Packages

As of this writing, there are [1,853 registered Julia packages](https://pkg.julialang.org/), and [thousands more available on Github](https://github.com/search?utf8=%E2%9C%93&q=language%3Ajulia&type=). To install a registered package, use `Pkg.add()`: 

```julia
Pkg.add("Colors")
```

To load an installed package and bring its functions and types into your workspace, you can use `using`: 

In [30]:
using Colors

In [31]:
distinguishable_colors(10)

In [32]:
rand(RGB{Float32}, 5, 5)

You can install any package from Github (or any other git hosting service) with `Pkg.clone()`: 

```julia
Pkg.clone("https://github.com/rdeits/DynamicWalking2018.jl")
```

# Julia Plays Well with Others

Julia is a great language, but sometimes you need to use an existing tool rather than re-implementing it. Fortunately, it's very easy to call C, FORTRAN, and Python code directly from Julia. 

## Calling C and FORTRAN from Julia

Julia has built-in support for calling C and FORTRAN functions: https://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/

For example, let's get the current CPU time using the C standard library `libc`: 

In [33]:
ccall((:clock, "libc"), Int32, ())

19551588

Julia even knows how to convert certain types like Arrays and Strings to their C equivalents: 

In [34]:
ccall((:strcmp, "libc"), Cint, (Cstring, Cstring), "hello", "hello")

0

# Calling Python from Julia

Python support is provided by the [PyCall.jl](https://github.com/JuliaPy/PyCall.jl) package. To install it, just run: 

```julia
Pkg.add("PyCall")
```

In [35]:
using PyCall

In [36]:
@pyimport datetime

In [37]:
datetime.datetime[:today]()

2018-05-24T09:12:48.441

Next, we'll show off Julia's performance compared to C and Python... 